angular.module('PlayerMappings', [])
.factory('Players', ['$resource', function($resource) {
	return $resource('/rest/players/:player');
}])
.factory('PlayerService', ['Players', function(Players) {
	var playerResultMap = {};
	var playerMap = {
<<<<<<< HEAD
			"": "yazid-abuanzeh",
			"ra": "raoul-adler",
			"": "diego-adolf",
			"": "oliver-aeschlimann",
			"": "filip-anastasovski",
			"": "thomas-anderegg",
			"": "mirjana-andovska",
			"": "elisaveta-andreeva",
			"": "emilija-andreevska",
			"": "martin-angelovski",
			"": "aleksandar-apostolov",
			"": "vladimir-arsov",
			"": "slavcho-arsovski",
			"sas": "sebastian-asler",
			"": "valentina-atanaskova",
			"": "goran-atanasovski",
			"": "viktor-atanasovski",
			"pa": "patrik-aufdermauer",
			"": "goran-bakraceski",
			"": "sabine-bamert",
			"": "thomas-baumann",
			"ibi": "iwan-birrer",
			"": "reto-bodenmann",
			"": "zoran-bogdanovski",
			"": "nidhal-boumaiza",
			"": "jean-claude-brantschen",
			"mbr": "michael-brantschen",
			"": "peter-brantschen",
			"jb": "jason-brazile",
			"": "gabriele-brechbuehl",
			"rb": "ronnie-brunner",
			"": "igor-bulovski",
			"": "raphael-buechler",
			"abu": "angela-buehler",
			"": "friedemann-buergel",
			"ac": "antonio-caliano",
			"": "emil-cepunjoski",
			"": "pance-cavkovski",
			"": "claudia-chini",
			"": "aleksandar-chochovski",
			"": "elena-chovikj",
			"": "daniel-clausen",
			"": "corsin-conzett",
			"": "andrej-cvetanovski",
			"": "goran-cvetkoski",
			"": "martin-cvetkov",
			"": "viktor-cvetkovik",
			"": "ostoja-cvijik",
			"jc": "joshy-cyriac",
			"": "marija-dacevska",
			"": "stephan-dambo",
			"": "aneta-damceska",
			"": "kristina-damjanoska",
			"": "domenico-de-stefano",
			"cd": "corsin-decurtins",
			"pde": "philipp-denzler",
			"sdk": "stephan-dick",
			"": "markus-dietrich",
			"sdi": "simon-dietschi",
			"": "jean-pierre-dillier",
			"": "damjan-dimitrov",
			"": "marija-dimovska",
			"": "levente-dobszay",
			"": "krume-dolnenec",
			"": "walter-duss",
			"": "jacqueline-duvoisin",
			"": "evelyn-daerendinger",
			"": "patrick-ehrensperger",
			"dei": "daniel-eichhorn",
			"": "diana-estermann",
			"": "michael-fahrni",
			"": "claudio-fava",
			"rfi": "roman-fischer",
			"": "priska-forrer",
			"mf": "mike-franz",
			"": "peter-frick",
			"": "rolf-frieden",
			"": "andreas-fritschy",
			"": "georg-fromherz",
			"": "thomas-fromherz",
			"sfu": "stefan-furrer",
			"": "marco-fuellemann",
			"": "goran-gajduk",
			"mig": "michael-gassmann",
			"": "natasha-gavrovska",
			"": "thomas-geier",
			"": "igor-geshoski",
			"rgi": "reto-giger",
			"": "aleksandar-gizarovski",
			"": "vladimir-gjokjevski",
			"": "vlado-gjorgjiev",
			"rgr": "reto-grob",
			"": "viktor-grozdanovski",
			"rg": "ramon-grunder",
			"": "john-guthoerl",
			"bg": "baris-guec",
			"wh": "wolfgang-habicht",
			"": "thierry-hafner",
			"jh": "joachim-hagger",
			"": "urs-hardegger",
			"": "maya-haug",
			"": "nicola-hefti",
			"bhe": "beat-heggli",
			"fhe": "florian-hengartner",
			"mhe": "martin-hermann",
			"rhe": "reto-heusser",
			"": "adrian-heydecker",
			"": "dominik-hiltbrunner",
			"jhi": "joel-hirano",
			"aho": "andi-hotz",
			"": "aleksandra-hristov",
			"bh": "benno-haefliger",
			"": "blaze-iliev",
			"": "bozidar-ilievski",
			"": "ivan-ilievski",
			"aim": "alexander-imfeld",
			"": "zarko-ivanoski",
			"oi": "ognen-ivanovski",
			"": "maja-jankuloska",
			"aj": "alexander-josef",
			"": "nadica-jovanovska",
			"": "jovan-jovanovski",
			"": "matthias-junker",
			"mj": "martin-jaeger",
			"rj": "roger-jaeggi",
			"": "kandiah",
			"": "jana-karcheska",
			"aka": "andreas-karrer",
			"": "daniel-kaufmann",
			"dke": "daniel-kellenberger",
			"sk": "stephan-keller",
			"mke": "marcel-kessler",
			"": "marjan-kindalov",
			"": "rolf-koch",
			"": "peter-kohler",
			"": "jovan-kolov",
			"": "suzana-kordumova",
			"": "toni-kostov",
			"": "dean-kostovski",
			"": "valentina-koteva",
			"": "sascha-kuhn",
			"aku": "anna-pitschna-kunz",
			"": "christian-kunz",
			"": "vojche-kushevski",
			"": "zlatko-kuvendziski",
			"ul": "urs-laub",
			"": "zhivko-lazarov",
			"": "oliver-lazoroski",
			"": "trajche-lazovski",
			"": "dirk-leiner",
			"sl": "simon-leo",
			"mli": "matthias-liechti",
			"": "vito-liloia",
			"": "katerina-ljubevska",
			"": "remi-locherer",
			"": "duy-ngoc-mai",
			"mma": "mark-maier",
			"om": "ovidio-mallo",
			"": "kevin-marbacher",
			"wm": "wolfgang-marent",
			"": "daniel-margreth",
			"": "spase-markovski",
			"pm": "philippe-marschall",
			"tmi": "thomas-marti",
			"": "giancarlo-massari",
			"sm": "sandra-mayer",
			"mme": "martin-meier",
			"mmy": "michael-meyer",
			"": "louise-miedaner",
			"": "orce-mihailov",
			"": "ivan-milanov",
			"": "kiril-milev",
			"vmi": "vasko-milevski",
			"": "pece-milosev",
			"": "slobodan-minov",
			"": "zoran-mirchevski",
			"": "boban-mitovski",
			"": "martin-mitrevski",
			"": "mitko-mitrov",
			"": "kristin-mock",
			"cm": "cla-monsch",
			"": "adrian-morgenegg",
			"": "bjoern-mosler",
			"cma": "christian-maeder",
			"": "thomas-maeder",
			"": "lara-muehlemann",
			"": "peter-mueller",
			"": "nikola-naumchevski",
			"": "tina-nestoroska",
			"": "christoph-neuhaus",
			"cni": "christoph-niemz",
			"": "zdravko-nikolovski",
			"an": "aleksandar-nikov",
			"so": "stefan-odendahl",
			"": "david-oetiker",
			"": "sander-ouwendijk",
			"": "jordan-palikrushev",
			"": "lazar-pancevski",
			"": "suzana-pasharikovska",
			"": "vasja-pavlov",
			"": "jasmina-pazardjievska",
			"": "tome-pejoski",
			"mp": "michael-pellaton",
			"": "lucy-pelzer",
			"": "slobodan-percuklieski",
			"": "rafael-perez",
			"": "stefanija-peroska",
			"": "goran-peshanski",
			"": "vlado-peshov",
			"": "tobias-peter",
			"": "aleksandar-petreski",
			"": "aleksandar-petrov",
			"": "aleksandar-petrovski",
			"": "aleksandar-petrusevski",
			"": "jens-piesbergen",
			"": "bojana-popovska",
			"rpr": "remo-preuss",
			"": "irena-radoeshka",
			"": "kate-rageth",
			"": "toni-rajkovski",
			"": "micaela-raschle",
			"": "michael-reichstein",
			"": "frosina-remenska",
			"": "beda-rickenbacher",
			"": "simon-riedener",
			"": "nathalie-ringgenberg",
			"": "beat-ris",
			"": "ana-risteska",
			"": "riste-ristevski",
			"": "aleksandar-ristov",
			"": "jacqueline-rohner",
			"": "felix-romer",
			"": "werner-roos",
			"": "raphael-roth",
			"": "rudolf-roth",
			"": "joel-roth",
			"": "erich-ruf",
			"sr": "stefan-rufer",
			"": "sandra-ruzicic",
			"": "cyrill-schenkel",
			"": "ralph-schenkel",
			"": "thomas-schenkel",
			"": "melanie-schmid",
			"": "patrick-schorno",
			"": "sebastian-schrepfer",
			"hs": "hans-schriber",
			"usc": "ulrich-schwar",
			"dsc": "daniel-schaedler",
			"csh": "christian-schaetti",
			"msh": "michele-schaeuble",
			"kse": "kevin-seidler",
			"": "angelika-seiler",
			"": "brigitte-seiler",
			"": "nako-siskov",
			"ys": "yannick-signer",
			"": "andon-sikavica",
			"": "igor-simevski",
			"": "vladimir-simjanoski",
			"": "boris-simovski",
			"cvs": "cvetanka-smileska",
			"": "jordan-soklevski",
			"nko": "nathanael-sommer",
			"": "sonja-spaar",
			"rsp": "roman-spycher",
			"jst": "jacques-stadler",
			"": "zlatko-stamatov",
			"": "makedonka-stamatova",
			"": "peco-stanoev",
			"": "peter-stegemann",
			"": "marcel-steinmann",
			"": "vladimir-stojov",
			"": "juerg-straub",
			"": "angela-stricker",
			"msr": "marcel-stoer",
			"": "igor-sudijovski",
			"": "zoltan-szekely",
			"": "muzelife-tairi",
			"": "elena-temelkovska",
			"": "gorazd-titizov",
			"": "aleksandar-toshevski",
			"": "maja-trajanoska",
			"": "vladimir-trajkovski",
			"st": "stefan-tramm",
			"": "tobias-trusch",
			"tt": "thomas-troescher",
			"": "stojanco-tudzarski",
			"": "vithusiya-ulagarajah",
			"": "tanja-uzunova",
			"": "ivan-valentin",
			"mv": "markus-vaterlaus",
			"av": "andrej-vckovski",
			"": "valerija-velinovska",
			"": "tome-velkov",
			"": "attila-vizhanyo",
			"rv": "regina-vogt",
			"hr": "hansruedi-vondermuehll",
			"cw": "christian-waldvogel",
			"rwe": "roland-weiss",
			"rw": "ralph-wildhaber",
			"yw": "yannick-winiger",
			"tza": "thomas-zangerl",
			"": "ljubomir-zivanovic",
			"": "mathias-zimmermann",
			"fa": "franziska-zingg",
			"": "peter-zurbruegg"
=======
	    "pz" : "peter-zurbruegg",
	    "st" : "stefan-tramm",
	    "pmu" : "peter-mueller",
	    "th" : "thierry-hafner",
	    "ts" : "thomas-schenkel",
	    "mig" : "michael-gassmann",
	    "mf" : "mike-franz",
	    "pa" : "patrik-aufdermauer",
	    "jb" : "jason-brazile",
	    "rb" : "ronnie-brunner",
	    "xfu" : "felix-bucher",
	    "tg" : "thomas-geier",
	    "rg" : "ramon-grunder",
	    "jh" : "joachim-hagger",
	    "xsh" : "simon-hefti",
	    "pk" : "peter-kohler",
	    "jp" : "jens-piesbergen",
	    "rs" : "ralph-schenkel",
	    "js" : "juerg-straub",
	    "av" : "andrej-vckovski",
	    "hr" : "hansruedi-vondermuehll",
	    "ul" : "urs-laub",
	    "sfu" : "stefan-furrer",
	    "cd" : "corsin-decurtins",
	    "pb" : "peter-brantschen",
	    "uh" : "urs-hardegger",
	    "xri" : "roland-sailer",
	    "aka" : "andreas-karrer",
	    "rw" : "ralph-wildhaber",
	    "so" : "stefan-odendahl",
	    "mst" : "marcel-steinmann",
	    "gb" : "gabriele-brechbuehl",
	    "jr" : "jacqueline-rohner",
	    "xdb" : "daniel-bareiss",
	    "xzs" : "zbynek-sykora",
	    "mbr" : "michael-brantschen",
	    "rgi" : "reto-giger",
	    "rsp" : "roman-spycher",
	    "mj" : "martin-jaeger",
	    "xhg" : "hanspeter-graenicher",
	    "msr" : "marcel-stoer",
	    "do" : "david-oetiker",
	    "sr" : "stefan-rufer",
	    "nk" : "nathalie-ringgenberg",
	    "xbu" : "markus-buechel",
	    "tf" : "thomas-fromherz",
	    "gf" : "georg-fromherz",
	    "ldy" : "levente-dobszay",
	    "wd" : "walter-duss",
	    "mme" : "martin-meier",
	    "tt" : "thomas-troescher",
	    "xst" : "mattias-steinholtz",
	    "xdv" : "daniel-volkart",
	    "sru" : "sandra-ruzicic",
	    "mp" : "michael-pellaton",
	    "dsc" : "daniel-schaedler",
	    "xja" : "jacqueline-aebi",
	    "om" : "ovidio-mallo",
	    "sk" : "stephan-keller",
	    "mfa" : "michael-fahrni",
	    "cc" : "claudia-chini",
	    "rwe" : "roland-weiss",
	    "sba" : "sabine-bamert",
	    "rv" : "regina-vogt",
	    "dcl" : "daniel-clausen",
	    "fr" : "felix-romer",
	    "dei" : "daniel-eichhorn",
	    "cm" : "cla-monsch",
	    "jst" : "jacques-stadler",
	    "xmn" : "matthias-nicolet",
	    "xak" : "andreas-knobel",
	    "mke" : "marcel-kessler",
	    "rbo" : "reto-bodenmann",
	    "aim" : "alexander-imfeld",
	    "xcr" : "candid-rutz",
	    "bsr" : "brigitte-seiler",
	    "mmy" : "michael-meyer",
	    "rgr" : "reto-grob",
	    "pe" : "patrick-ehrensperger",
	    "jd" : "jacqueline-duvoisin",
	    "tmi" : "thomas-marti",
	    "pm" : "philippe-marschall",
	    "oa" : "oliver-aeschlimann",
	    "jc" : "joshy-cyriac",
	    "ac" : "antonio-caliano",
	    "mdi" : "markus-dietrich",
	    "iv" : "ivan-valentin",
	    "ibi" : "iwan-birrer",
	    "fbu" : "friedemann-buergel",
	    "wh" : "wolfgang-habicht",
	    "dke" : "daniel-kellenberger",
	    "jbr" : "jean-claude-brantschen",
	    "mhe" : "martin-hermann",
	    "ssp" : "sonja-spaar",
	    "dd" : "damjan-dimitrov",
	    "xps" : "peter-stulzer",
	    "kbn" : "kate-rageth",
	    "aj" : "alexander-josef",
	    "usc" : "ulrich-schwar",
	    "dmu" : "diana-estermann",
	    "rfi" : "roman-fischer",
	    "sm" : "sandra-mayer",
	    "xac" : "andrey-collison",
	    "as" : "angelika-seiler",
	    "xaj" : "ales-jakubek",
	    "yw" : "yannick-winiger",
	    "cz" : "christof-zellweger",
	    "xhe" : "sascha-hegi",
	    "af" : "andreas-fritschy",
	    "rlo" : "remi-locherer",
	    "dh" : "dominik-hiltbrunner",
	    "mti" : "muzelife-tairi",
	    "xsc" : "christian-schnider",
	    "jro" : "joel-roth",
	    "xdm" : "daniel-moser",
	    "xwe" : "marian-weisser",
	    "msd" : "melanie-schmid",
	    "xse" : "miroslav-senk",
	    "ta" : "thomas-anderegg",
	    "tza" : "thomas-zangerl",
	    "xtw" : "tim-walther",
	    "psc" : "patrick-schorno",
	    "cw" : "christian-waldvogel",
	    "nh" : "nicola-hefti",
	    "ys" : "yannick-signer",
	    "br" : "beda-rickenbacher",
	    "xsm" : "sven-mader",
	    "xnn" : "nico-negri",
	    "xml" : "marco-longhitano",
	    "mzi" : "mathias-zimmermann",
	    "xmm" : "martin-moser",
	    "rfn" : "rolf-frieden",
	    "sdi" : "simon-dietschi",
	    "fa" : "franziska-zingg",
	    "xmc" : "martin-mcnulty",
	    "xjc" : "jan-chmelar",
	    "xsj" : "pavel-stejgerle",
	    "xpv" : "pavel-safranek",
	    "xjk" : "jan-krebs",
	    "xmr" : "maurice-ray",
	    "xcb" : "carmen-betschart",
	    "pfr" : "peter-frick",
	    "msh" : "michele-schaeuble",
	    "kkh" : "kkandiah",
	    "ska" : "kandiah",
	    "csl" : "cyrill-schenkel",
	    "ed" : "evelyn-daerendinger",
	    "mre" : "micaela-raschle",
	    "dma" : "daniel-margreth",
	    "kse" : "kevin-seidler",
	    "xas" : "joonas-asikainen",
	    "xgs" : "giancarlo-scrugli",
	    "xkw" : "katrin-wassmuth",
	    "mfn" : "marco-fuellemann",
	    "nko" : "nathanael-sommer",
	    "rr" : "raphael-roth",
	    "xck" : "christian-kohler",
	    "rko" : "rolf-koch",
	    "csh" : "christian-schaetti",
	    "sdk" : "stephan-dick",
	    "xji" : "joel-ineichen",
	    "dnm" : "duy-ngoc-mai",
	    "rbu" : "raphael-buechler",
	    "ttr" : "tobias-trusch",
	    "lpe" : "lucy-pelzer",
	    "sou" : "sander-ouwendijk",
	    "dad" : "diego-adolf",
	    "xra" : "robert-saniga",
	    "pde" : "philipp-denzler",
	    "rpe" : "rafael-perez",
	    "pfo" : "priska-forrer",
	    "ach" : "aleksandar-chochovski",
	    "mju" : "matthias-junker",
	    "xjt" : "jonas-tappolet",
	    "xhz" : "hansueli-zuercher",
	    "xtz" : "thomas-zaedow",
	    "ra" : "raoul-adler",
	    "aku" : "anna-pitschna-kunz",
	    "xka" : "katja-ambord",
	    "ir" : "irena-radoeshka",
	    "rri" : "riste-ristevski",
	    "abu" : "angela-buehler",
	    "sl" : "simon-leo",
	    "mv" : "markus-vaterlaus",
	    "jg" : "john-guthoerl",
	    "fhe" : "florian-hengartner",
	    "hs" : "hans-schriber",
	    "mha" : "maya-haug",
	    "mli" : "matthias-liechti",
	    "iil" : "ivan-iljkic",
	    "mdm" : "marija-dimovska",
	    "avi" : "attila-vizhanyo",
	    "bg" : "baris-guec",
	    "bmo" : "bjoern-mosler",
	    "lmu" : "lara-muehlemann",
	    "jpd" : "jean-pierre-dillier",
	    "tba" : "thomas-baumann",
	    "sku" : "sascha-kuhn",
	    "xsa" : "stefan-arnold",
	    "zsz" : "zoltan-szekely",
	    "wm" : "wolfgang-marent",
	    "xha" : "maria-hahnloser",
	    "nb" : "nidhal-boumaiza",
	    "is" : "igor-simevski",
	    "isu" : "igor-sudijovski",
	    "ig" : "igor-geshoski",
	    "zla" : "zhivko-lazarov",
	    "dsp" : "daniel-spasovski",
	    "xpe" : "pietro-pedrozzi",
	    "gma" : "giancarlo-massari",
	    "zm" : "zoran-mirchevski",
	    "sri" : "simon-riedener",
	    "vp" : "vlado-peshov",
	    "dle" : "dirk-leiner",
	    "aho" : "andi-hotz",
	    "rpr" : "remo-preuss",
	    "jhi" : "joel-hirano",
	    "kma" : "kevin-marbacher",
	    "brs" : "beat-ris",
	    "tpt" : "tobias-peter",
	    "xtk" : "tom-kool",
	    "mma" : "mark-maier",
	    "sar" : "slavcho-arsovski",
	    "ibu" : "igor-bulovski",
	    "jpa" : "jordan-palikrushev",
	    "rj" : "roger-jaeggi",
	    "xjf" : "jan-fornusek",
	    "vli" : "vito-liloia",
	    "xmd" : "martin-damek",
	    "aap" : "aleksandar-apostolov",
	    "smr" : "spase-markovski",
	    "iii" : "ivan-ilievski",
	    "mae" : "martin-angelovski",
	    "mja" : "maja-jankuloska",
	    "rro" : "rudolf-roth",
	    "jj" : "jovan-jovanovski",
	    "lm" : "louise-miedaner",
	    "cne" : "christoph-neuhaus",
	    "vu" : "vithusiya-ulagarajah",
	    "xss" : "mail-schulz",
	    "vpa" : "vasja-pavlov",
	    "tmr" : "thomas-maeder",
	    "sas" : "sebastian-asler",
	    "mcv" : "martin-cvetkov",
	    "xfe" : "sophie-fedier",
	    "xbf" : "bernd-fellinghauer",
	    "dkn" : "daniel-kaufmann",
	    "bhe" : "beat-heggli",
	    "xgc" : "gustavo-colliard",
	    "er" : "erich-ruf",
	    "ck" : "christian-kunz",
	    "dde" : "domenico-de-stefano",
	    "fan" : "filip-anastasovski",
	    "ean" : "emilija-andreevska",
	    "cni" : "christoph-niemz",
	    "ssc" : "sebastian-schrepfer",
	    "ga" : "goran-atanasovski",
	    "amo" : "adrian-morgenegg",
	    "xmg" : "marcel-engelberger",
	    "cco" : "corsin-conzett",
	    "cfa" : "claudio-fava",
	    "nna" : "nikola-naumchevski",
	    "sda" : "stephan-dambo",
	    "xma" : "marcel-wirth",
	    "xsb" : "samuel-christian-bernet",
	    "xmh" : "michael-schmidt",
	    "jpz" : "jasmina-pazardjievska",
	    "psn" : "peter-stegemann",
	    "cma" : "christian-maeder",
	    "ahk" : "adrian-heydecker",
	    "ari" : "ana-risteska",
	    "kmo" : "kristin-mock",
	    "xjb" : "jonas-baeckman",
	    "vst" : "vladimir-stojov",
	    "xcl" : "chantal-landis",
	    "ya" : "yazid-abuanzeh",
	    "xce" : "catalin-ehrmann",
	    "xay" : "asli-yaman",
	    "smi" : "slobodan-minov",
	    "gp" : "goran-peshanski",
	    "xjs" : "jaroslav-sendler",
	    "ead" : "elisaveta-andreeva",
	    "xnb" : "noel-blessing",
	    "xbd" : "barbara-dravec",
	    "ssm" : "stojan-stamkov",
	    "vda" : "vlatko-danchev",
	    "xbo" : "eszter-boerzsoenyi",
	    "mdu" : "madelein-duplessis",
	    "csa" : "charles-salameh",
	    "xjl" : "janine-lutz",
	    "lst" : "ljupcho-stojcheski",
	    "xcw" : "charles-windlin",
	    "ha" : "hamad-albadi",
	    "xuh" : "urs-herger",
	    "xla" : "ludwig-antilli",
	    "xsg" : "sebastian-gubser",
	    "mat" : "margrit-angst",
	    "mse" : "makedonka-stamatova",
	    "an" : "aleksandar-nikov",
	    "km" : "kiril-milev",
	    "oi" : "ognen-ivanovski",
	    "kd" : "krume-dolnenec",
	    "jk" : "jovan-kolov",
	    "oc" : "ostoja-cvijik",
	    "vs" : "vladimir-simjanoski",
	    "mta" : "maja-trajanoska",
	    "lz" : "ljubomir-zivanovic",
	    "tv" : "tome-velkov",
	    "va" : "valentina-atanaskova",
	    "mmi" : "mitko-mitrov",
	    "sp" : "slobodan-percuklieski",
	    "stu" : "stojanco-tudzarski",
	    "vg" : "vladimir-gjokjevski",
	    "kda" : "kristina-damjanoska",
	    "vc" : "viktor-cvetkovik",
	    "gt" : "gorazd-titizov",
	    "nsi" : "nako-siskov",
	    "pst" : "peco-stanoev",
	    "ar" : "aleksandar-ristov",
	    "vmi" : "vasko-milevski",
	    "ec" : "emil-cepunjoski",
	    "ahr" : "aleksandra-hristov",
	    "ad" : "aneta-damceska",
	    "kl" : "katerina-ljubevska",
	    "im" : "ivan-milanov",
	    "spe" : "stefanija-peroska",
	    "bi" : "bozidar-ilievski",
	    "tk" : "toni-kostov",
	    "gc" : "goran-cvetkoski",
	    "lpa" : "lazar-pancevski",
	    "acv" : "andrej-cvetanovski",
	    "ap" : "aleksandar-petreski",
	    "man" : "mirjana-andovska",
	    "pmi" : "pece-milosev",
	    "et" : "elena-temelkovska",
	    "asi" : "andon-sikavica",
	    "mki" : "marjan-kindalov",
	    "ape" : "aleksandar-petrusevski",
	    "zn" : "zdravko-nikolovski",
	    "bil" : "blaze-iliev",
	    "zk" : "zlatko-kuvendziski",
	    "jso" : "jordan-soklevski",
	    "apt" : "aleksandar-petrov",
	    "fre" : "frosina-remenska",
	    "tr" : "toni-rajkovski",
	    "vat" : "viktor-atanasovski",
	    "pca" : "pance-cavkovski",
	    "var" : "vladimir-arsov",
	    "agi" : "aleksandar-gizarovski",
	    "gg" : "goran-gajduk",
	    "skr" : "suzana-kordumova",
	    "dko" : "dean-kostovski",
	    "bsm" : "boris-simovski",
	    "spa" : "suzana-pasharikovska",
	    "vk" : "valentina-koteva",
	    "tpj" : "tome-pejoski",
	    "vtr" : "vladimir-trajkovski",
	    "vgr" : "viktor-grozdanovski",
	    "zb" : "zoran-bogdanovski",
	    "zi" : "zarko-ivanoski",
	    "apr" : "aleksandar-petrovski",
	    "tu" : "tanja-uzunova",
	    "tne" : "tina-nestoroska",
	    "ech" : "elena-chovikj",
	    "vgj" : "vlado-gjorgjiev",
	    "zst" : "zlatko-stamatov",
	    "jka" : "jana-karcheska",
	    "ol" : "oliver-lazoroski",
	    "csm" : "cvetanka-smileska",
	    "omi" : "orce-mihailov",
	    "tla" : "trajche-lazovski",
	    "vku" : "vojche-kushevski",
	    "mmt" : "martin-mitrevski",
	    "vv" : "valerija-velinovska",
	    "bm" : "boban-mitovski",
	    "nga" : "natasha-gavrovska",
	    "at" : "aleksandar-toshevski",
	    "bpo" : "bojana-popovska",
	    "bh" : "benno-haefliger",
	    "wr" : "werner-roos",
	    "xsv" : "sandra-vontobel",
	    "xnr" : "nicola-reggiori",
	    "xso" : "stamatis-stefanakos"
>>>>>>> acce7639eeb8fd04fb0e5f987e875e63b264dd9f

	};
	return {
		getPlayerPicture: function(shortname) {
			var playerName = playerMap[shortname];
			if (angular.isDefined(playerName) && shortname.length > 1) {
				console.log("Getting image address for ")
				return "http://www.netcetera.com/en/data/contacts/Netcetera/" + playerName + "/photo/photo.jpg";
			} else {
				return "images/person2.png";
			}
		}
	    
	 	
	}
}]);
